### PR TITLE
Display clean error message when meteor not found in $PATH

### LINKED ISSUE #157: Meteor not in Path
When meteor is not in the path, the error message displayed is not clear : 

Error: spawn ENOENT

### PR DESCRIPTION
**Pull request by theworkflow**
Closes #157

### CODE REVIEW

**Comment by franvarney** [comment]
👍

File: test/build.js [hunk 1]
```diff
@@ -118,4 +118,18 @@ describe('build', function () {
...
   });
+
+  it('return clear error message when Meteor not installed', function (done) {
+    var message = [
+      'Meteor not in path.',
+      'Please make sure Meteor is installed properly.'
+    ].join(' ');
+
+    Build({}, function (err) {
+      expect(err.message).to.equal(message);
```
Comment (jackboberg) [inline test/build.js]: To allow for subtle changes to the message without needing updated tests, you could try something like:

`expect(err.message).to.include('Meteor not in $PATH')`

_also, I think it should be `$PATH` not `path`_

**Comment by jackboberg** [comment]
👍 w/ comments
